## Ryan Thomas -- R Programming Programming Assignment 2

## makeCacheMatrix makes a list object (to allow for proper lexical scoping advantages)
## of mutators + accessors as well as the data which will be inverted, when first called
## it will clear any currently-cached inverse in order to make sure it has a clean run

makeCacheMatrix <- function(x = matrix()) {
  inverse <- NULL
  set <- function(y) {
    x <<- y
    inverse <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) inverse <<- solve
  getinverse <- function() inverse
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}


## cacheSolve takes the data in the "matrix" object generated by makeCacheMatrix
## (including any already-cached inverse) and inverts it if there is no cached inverse.
## It then caches the inverse in the "matrix" object

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inverse <- x$getinverse()
  if(!is.null(inverse)) {
    message("getting cached data")
    return(inverse)
  }
  data <- x$get()
  inverse <- solve(data, ...)
  x$setinverse(inverse)
  inverse
}
